# render.yaml
services:
  - type: web
    name: loan-backend
    env: python
    repo: https://github.com/karthik-raj10/data-analysis
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://karthik:Kar%4018831@cluster0.6nj9kmm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: DB_NAME
        value: test_database
      - key: CORS_ORIGINS
        value: "*"
